title: Bunting News
author: Catherine
email: mombunting@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Family Blog for Phoenix Bunting Clan

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  momBunting # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
theme: minima
